/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlVeterinario;
import modelo.Veterinario;

/**
 *
 * @author angela_maria.marin
 */
public class InsertarVeterinario extends javax.swing.JFrame {

    /**
     * Creates new form veterinario
     */
    public InsertarVeterinario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jt_nom1veterinario = new javax.swing.JTextField();
        Bagregarveterinario = new javax.swing.JButton();
        Blimpiarveterinario = new javax.swing.JButton();
        jt_nom2veterinario = new javax.swing.JTextField();
        jt_ape1veterinario = new javax.swing.JTextField();
        jt_ape2veterinario = new javax.swing.JTextField();
        jt_edadveterinario = new javax.swing.JTextField();
        jt_correoveterinario = new javax.swing.JTextField();
        jt_tel1veterinario = new javax.swing.JTextField();
        jt_tel2veterinario = new javax.swing.JTextField();
        jt_dirveterinario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Jidveterinario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Batrasveterinario = new javax.swing.JButton();
        Bcerrarveterinario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(150, 150, 150));
        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setText("Primer nombre");

        jLabel2.setText("Segundo nombre");

        jLabel3.setText("Primer apellido");

        jLabel4.setText("Segundo apellido");

        jLabel6.setText("Edad");

        jLabel7.setText("Correo");

        jLabel8.setText("Teléfono 1");

        jLabel9.setText("Teléfono 2");

        jLabel10.setText("Dirección");

        jt_nom1veterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_nom1veterinarioActionPerformed(evt);
            }
        });

        Bagregarveterinario.setText("Agregar");
        Bagregarveterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagregarveterinarioActionPerformed(evt);
            }
        });

        Blimpiarveterinario.setText("Limpiar");
        Blimpiarveterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlimpiarveterinarioActionPerformed(evt);
            }
        });

        jt_nom2veterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_nom2veterinarioActionPerformed(evt);
            }
        });

        jt_ape1veterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_ape1veterinarioActionPerformed(evt);
            }
        });

        jt_ape2veterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_ape2veterinarioActionPerformed(evt);
            }
        });

        jt_edadveterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_edadveterinarioActionPerformed(evt);
            }
        });

        jt_correoveterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_correoveterinarioActionPerformed(evt);
            }
        });

        jt_tel1veterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_tel1veterinarioActionPerformed(evt);
            }
        });

        jt_tel2veterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_tel2veterinarioActionPerformed(evt);
            }
        });

        jt_dirveterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_dirveterinarioActionPerformed(evt);
            }
        });

        jLabel5.setText("Identificación");

        Jidveterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JidveterinarioActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("INSERTAR VETERINARIO");

        Batrasveterinario.setText("Atras");
        Batrasveterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatrasveterinarioActionPerformed(evt);
            }
        });

        Bcerrarveterinario.setText("Cerrar");
        Bcerrarveterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcerrarveterinarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(Bagregarveterinario)
                        .addGap(50, 50, 50)
                        .addComponent(Blimpiarveterinario)
                        .addGap(37, 37, 37)
                        .addComponent(Batrasveterinario)
                        .addGap(46, 46, 46)
                        .addComponent(Bcerrarveterinario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel11)))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jt_nom1veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_nom2veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_ape1veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jidveterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jt_ape2veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_dirveterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_tel2veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_correoveterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_edadveterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_tel1veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Jidveterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jt_edadveterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jt_nom1veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jt_correoveterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_nom2veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jt_tel1veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_ape1veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jt_tel2veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jt_ape2veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jt_dirveterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bagregarveterinario)
                    .addComponent(Batrasveterinario)
                    .addComponent(Blimpiarveterinario)
                    .addComponent(Bcerrarveterinario))
                .addGap(63, 63, 63))
        );

        jLabel6.getAccessibleContext().setAccessibleName("jLabel6");
        jLabel7.getAccessibleContext().setAccessibleName("jLabel7");
        jLabel8.getAccessibleContext().setAccessibleName("jLabel8");
        jLabel9.getAccessibleContext().setAccessibleName("jLabel9");
        jLabel10.getAccessibleContext().setAccessibleName("jLabel10");
        jt_nom1veterinario.getAccessibleContext().setAccessibleName("idveterinario");
        Bagregarveterinario.getAccessibleContext().setAccessibleName("agregar");
        Blimpiarveterinario.getAccessibleContext().setAccessibleName("limpiar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_nom1veterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_nom1veterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_nom1veterinarioActionPerformed

    private void BlimpiarveterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlimpiarveterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlimpiarveterinarioActionPerformed

    private void jt_nom2veterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_nom2veterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_nom2veterinarioActionPerformed

    private void jt_ape1veterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_ape1veterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_ape1veterinarioActionPerformed

    private void jt_ape2veterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_ape2veterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_ape2veterinarioActionPerformed

    private void jt_edadveterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_edadveterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_edadveterinarioActionPerformed

    private void jt_correoveterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_correoveterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_correoveterinarioActionPerformed

    private void jt_tel1veterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_tel1veterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_tel1veterinarioActionPerformed

    private void jt_tel2veterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_tel2veterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_tel2veterinarioActionPerformed

    private void jt_dirveterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_dirveterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_dirveterinarioActionPerformed

    private void BagregarveterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagregarveterinarioActionPerformed
     String nombrev1;
     String nombrev2;
     String apellidov1;
     String apellidov2;
     int edadv;
     String correov;
     String telv1;
     String telv2;
     String dirv;
     int id_veterinario;
     
     nombrev1=jt_nom1veterinario.getText();
     nombrev2=jt_nom2veterinario.getText();
     apellidov1=jt_ape1veterinario.getText();
     apellidov2=jt_ape2veterinario.getText();
     edadv=Integer.parseInt(jt_edadveterinario.getText());
     correov=jt_correoveterinario.getText();
     telv1=jt_tel1veterinario.getText();
     telv2=jt_tel2veterinario.getText();
     dirv=jt_dirveterinario.getText();
     id_veterinario=Integer.parseInt(Jidveterinario.getText());
     
     
       ControlVeterinario objce=new ControlVeterinario();
        Veterinario obje=new Veterinario(id_veterinario,nombrev1,nombrev2,apellidov1,apellidov2,edadv,correov,telv1,telv2,dirv);
        boolean f=objce.insertarVeterinario(obje);
        
        if(f){
            
            System.out.println("Se inserto el veterinario");
        }else{
            System.out.println("No se inserto el veteriono");
        }
    }//GEN-LAST:event_BagregarveterinarioActionPerformed

    private void JidveterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JidveterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JidveterinarioActionPerformed

    private void BatrasveterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatrasveterinarioActionPerformed
        InsertarCuidador abrir = new InsertarCuidador();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BatrasveterinarioActionPerformed

    private void BcerrarveterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcerrarveterinarioActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BcerrarveterinarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarVeterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bagregarveterinario;
    private javax.swing.JButton Batrasveterinario;
    private javax.swing.JButton Bcerrarveterinario;
    private javax.swing.JButton Blimpiarveterinario;
    private javax.swing.JTextField Jidveterinario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jt_ape1veterinario;
    private javax.swing.JTextField jt_ape2veterinario;
    private javax.swing.JTextField jt_correoveterinario;
    private javax.swing.JTextField jt_dirveterinario;
    private javax.swing.JTextField jt_edadveterinario;
    private javax.swing.JTextField jt_nom1veterinario;
    private javax.swing.JTextField jt_nom2veterinario;
    private javax.swing.JTextField jt_tel1veterinario;
    private javax.swing.JTextField jt_tel2veterinario;
    // End of variables declaration//GEN-END:variables
}
