/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Ángela
 */
public class OpcionesModificar extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    public OpcionesModificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Bmodificaranimal = new javax.swing.JButton();
        Bmodificarcuidador = new javax.swing.JButton();
        Bmodificarhabitat = new javax.swing.JButton();
        Bmodificarveterinario = new javax.swing.JButton();
        Bmodificarespecie = new javax.swing.JButton();
        Bmodificarcerrar = new javax.swing.JButton();
        Batrasmodificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("MODIFICAR");

        Bmodificaranimal.setText("Animal");
        Bmodificaranimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmodificaranimalActionPerformed(evt);
            }
        });

        Bmodificarcuidador.setText("Cuidador");
        Bmodificarcuidador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmodificarcuidadorActionPerformed(evt);
            }
        });

        Bmodificarhabitat.setText("Habitat");
        Bmodificarhabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmodificarhabitatActionPerformed(evt);
            }
        });

        Bmodificarveterinario.setText("Veterinario");
        Bmodificarveterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmodificarveterinarioActionPerformed(evt);
            }
        });

        Bmodificarespecie.setText("Especie");

        Bmodificarcerrar.setText("Cerrar");
        Bmodificarcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmodificarcerrarActionPerformed(evt);
            }
        });

        Batrasmodificar.setText("Atras");
        Batrasmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatrasmodificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Bmodificarveterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bmodificaranimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bmodificarcuidador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bmodificarhabitat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bmodificarespecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Batrasmodificar)
                .addGap(18, 18, 18)
                .addComponent(Bmodificarcerrar)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Bmodificaranimal)
                .addGap(18, 18, 18)
                .addComponent(Bmodificarcuidador)
                .addGap(18, 18, 18)
                .addComponent(Bmodificarhabitat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bmodificarveterinario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bmodificarespecie)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bmodificarcerrar)
                    .addComponent(Batrasmodificar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BmodificaranimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmodificaranimalActionPerformed
        ModificarAnimal abrir = new ModificarAnimal();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BmodificaranimalActionPerformed

    private void BmodificarcuidadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmodificarcuidadorActionPerformed
        ModificarCuidador abrir = new ModificarCuidador();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BmodificarcuidadorActionPerformed

    private void BmodificarhabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmodificarhabitatActionPerformed
        ModificarHabitat abrir = new ModificarHabitat();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BmodificarhabitatActionPerformed

    private void BmodificarveterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmodificarveterinarioActionPerformed
        ModificarVeterinario abrir = new ModificarVeterinario();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BmodificarveterinarioActionPerformed

    private void BmodificarcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmodificarcerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BmodificarcerrarActionPerformed

    private void BatrasmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatrasmodificarActionPerformed
        Menu abrir = new Menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BatrasmodificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batrasmodificar;
    private javax.swing.JButton Bmodificaranimal;
    private javax.swing.JButton Bmodificarcerrar;
    private javax.swing.JButton Bmodificarcuidador;
    private javax.swing.JButton Bmodificarespecie;
    private javax.swing.JButton Bmodificarhabitat;
    private javax.swing.JButton Bmodificarveterinario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
